# Generated by Django 5.0.6 on 2024-07-03 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('defaultFaceFile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DiceFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.CharField(max_length=200)),
                ('dice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiceApp.dice')),
            ],
        ),
        migrations.CreateModel(
            name='DiceSounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.CharField(max_length=200)),
                ('dice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiceApp.dice')),
            ],
        ),
    ]
