# Generated by Django 5.0.6 on 2024-08-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='shakeSoundFile',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
